### ISSUE TITLE
minimum viable product

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#1]
- [x] public datacats release
- [x] datacats child environment feature: environments can have multiple child db/solr/web containers
- [x] nginx http router config: serve datacats children as subdomains
- [x] flask api for wrapping datacats commands
- [x] flask admin interface: create and remove children, set admin passwords
- [x] template multisite datacats environment: link back to project, tell users how to contact admins #19 

This is a meta-ticket to track the progress to a first release of ckan-multisite "0.1"

**Comment by waldoj** [comment]
:+1:

**Comment by JackMc** [comment]
https://github.com/datacats/datacats/pull/82 Work for point 2

**Comment by wardi** [comment]
Just merged multisite support into datacats master: https://github.com/datacats/datacats/pull/82

**Comment by waldoj** [comment]
:+1:

**Comment by JackMc** [comment]
So the documentation is lagging a little bit behind, but the current master allows you to:
- Create instances from the command line (using the `datacats init` CLI tool) and have them picked up by multisite and automatically configured for Nginx
- Add and remove instances
- Generate Nginx router configurations and place them in the right place
- start, stop, and get the status of containers from the "edit" pane of the Flask-admin interface

**Comment by JackMc** [comment]
Next Steps:
- [ ] Add ability to specify custom site domains that aren't just the site name
- [ ] Stylize things a little bit
- [x] Update documentation
- [ ] Test on dev server

**Comment by waldoj** [comment]
Sounds great!

**Comment by wardi** [comment]
Closing this as the major functionality is complete, we're working on polishing the interface and docs. If there's anyone looking to give early feedback, now would be a great time.

**Comment by waldoj** [comment]
I'll give it a spin on Monday!

**Comment by jqnatividad** [comment]
:+1:
