### ISSUE TITLE
problems setting up

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#10]
- [x] run.sh starts redis with the redis conf from /etc/redis causing a permission denied on the logs dir
  replacing with a relative "redis.conf" seems to work, but would be even better with a `basename $0`
- [x] old import db from admin.py causes failure, removing the import seems to work
- [x] no docs about having to create a datacats environment called "multisite"
- [x] `Error: [object Object]` shown when trying to start/stop/info on a site, along with logs:

```
127.0.0.1 - - [15/Jul/2015 14:16:24] "POST /api/v1/status HTTP/1.1" 409 -
127.0.0.1 - - [15/Jul/2015 14:16:43] "POST /api/v1/change_admin HTTP/1.1" 409 -
127.0.0.1 - - [15/Jul/2015 14:16:52] "POST /api/v1/stop HTTP/1.1" 409 -
```

**Comment by JackMc** [comment]
2: Fixed.

4: This was a problem where I changed to using the correct content-type and the AJAX API decided to be nice by parsing the JSON for me.

**Comment by JackMc** [comment]
3: I swear this was already there, but it definitely is now.

**Comment by JackMc** [comment]
1: Sorted

**Comment by JackMc** [comment]
Should be all clear now! :+1:
