### ISSUE TITLE
add --site-url to init param for datacats>1.0 compatibility

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#11]
Then when the datacats refactoring is done switch to whatever nicer interface we come up with

**Comment by JackMc** [comment]
We don't call init:
https://github.com/datacats/ckan-multisite/blob/master/ckan_multisite/task.py#L16

**Comment by wardi** [comment]
Oh, thanks. My remotes were set up wrong and I hadn't pulled the latest
