### ISSUE TITLE
add a trap to run.sh that kills the celery process when the script exits

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#12]

**Comment by JackMc** [comment]
2d72131b98c82232d4b578a52ef8b7e879ba6438 Had to do sudo because for some reason it runs as root...

**Comment by wardi** [comment]
That can't be right. Instead of killall, add the trap just after starting celery and have it kill the pid just sent into the background (`$!`).

**Comment by JackMc** [comment]
046a3e5333fe524a4f616b9120b0becf700455bc Should fix this

**Comment by wardi** [comment]
works great!
