### ISSUE TITLE
Can't tell what site we're editing in the admin

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#15]
The site name isn't visible on the interface until after user clicks start/stop/status

**Comment by JackMc** [comment]
42c24d1bc3af5d04a5912f978bfc49c83c5509c8 fixes this

It makes the three buttons for save/save&continue looks weird and indented, though

**Comment by wardi** [comment]
What do save, save&continue and cancel buttons do? Can they be removed from that page?

**Comment by JackMc** [comment]
c00d61657222e8a8a6382afbe76fc719a59b7409 Sorts this
