### ISSUE TITLE
Bundle the data.json extension to facilitate harvesting

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#18]
A common feature request for CKAN Multisite has been to bundle [the data.json extension](https://github.com/HHS/ckanext-datajson). Governments want to use this to make it easy for them to a) harvest all data from the CKAN Multisite sites that they host and b) make sure that all sites that they host have data catalogs that can be syndicated by Data.gov. It'd solve both of those problems at once if we could just include this in the stock configuration.

If this is something that you want to add as an end-of-pipe thing for a gov-specific version, if it's in some way bad to include that extension by default for _all_ sites running this, that's certainly A-OK by me.

**Comment by wardi** [comment]
@waldoj ckan-multisite is built on a single datacats environment, which includes all the installed extensions and base configuration. Every site will have the same extensions installed, including if the admin chooses, the data.json extension.

**Comment by wardi** [comment]
This does work right now, by the way, we're just ironing out the final interface wrinkles right now and we'll soon invite some early adopters to kick the tires :-)

**Comment by waldoj** [comment]
:+1: Great!
