### ISSUE TITLE
template datacats source dir

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#19]
For users setting up multisite for the first time who aren't already familiar with datacats we should have a default source dir+ckan extension that includes a message on the front page that
- indicates to end users that this site is part of a multisite ckan environment
- suggests where to look to customize the site templates (if they are the multisite admin)
- their multisite administrator can provide admin access to this specific site on request

Also include links back to this project and information about where to go to ask for support

**Comment by JackMc** [comment]
Proposed fix up on master
