### ISSUE TITLE
Install fails with Python error

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#20]
While stepping through [the installation process](https://github.com/datacats/ckan-multisite#setup) on a fresh EC2 Ubuntu 14.04 image, I ran `sudo pip install -r requirements.txt` which failed with this error:

```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yUzAqZ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/uwsgi
```

[Here's the entire install log](https://gist.github.com/waldoj/fc9b531f03b55abe9748).

**Comment by JackMc** [comment]
This software works much nicer if you have it installed in a virtualenv. Nevertheless, I'll take a look.

**Comment by JackMc** [comment]
Specifically `datacats` doesn't like being installed outside of a virtualenv

**Comment by JackMc** [comment]
Should be able to fix this by installing the `python-dev` package from the Ubuntu repositories.

**Comment by waldoj** [comment]
Ah, so "preferably in a virtualenv" means "_definitely_ in a virtualenv." :) Virtualenv confuses the hell out of me, so when I saw that I could skip that step to test this out, it seemed worth doing. I'll figure out how to use virtualenv and take another crack at this. Thanks!

**Comment by JackMc** [comment]
Sorry, was a little sleepy writing the instructions :)

**Comment by JackMc** [comment]
I will change that!

**Comment by waldoj** [comment]
I may well just be using virtualenv wrong, but I just created a virtualenv, moved CKAN Multisite into its directory, and ran `pip install` again, like such:

```
# virtualenv ckan
# mv ckan-multisite-master/ ckan/
# sudo pip install -r requirements.txt
```

It died with the same error. But, again, I may well just be using virtualenv wrong.

**Comment by JackMc** [comment]
Hi Waldo! Sorry if I'm not very responsive, 'tis a bank holiday up here in the not-so-cold north.

You shouldn't use `sudo` or run as root with virtualenvs, as it messes with the environment variables sometimes. You can activate a virtualenv you've created (therefore make it the provider of the `pip` and `python` tools, along with a couple others) like so:

```
source ckan/bin/activate
```

**Comment by waldoj** [comment]
You should definitely ignore me until it ceases to be a holiday. :)

**Comment by JackMc** [comment]
Any luck?

**Comment by waldoj** [comment]
No. :( I ran `virtualenv ckan`, then `source ckan/bin/activate`, put the contents of this repo in `ckan/ckan-multisite-master/`, moved into that directory, and ran `pip install -r requirements.txt`, which terminated with the same error.

I appreciate that CKAN Multisite is targeted at people comfortable with Virtualenv, so I'm sorry to be asking newbie questions.

**Comment by deniszgonjanin** [comment]
I feel that anyone with sufficient unix sysadmin skill should be able to set up multisite without too much hassle. We'll have to sort the virtualenv issues out. Do keep reporting issues

**Comment by JackMc** [comment]
Hm. Did you install the package `python-dev` from apt-get like this?:

```
apt-get install python-dev
```

**Comment by waldoj** [comment]
> I feel that anyone with sufficient unix sysadmin skill should be able to set up multisite without too much hassle. 

FWIW, I've been a Unix sysadmin for 20 years, starting with Slackware and working my way up through AIX, SCO, Red Hat, CentOS, and Ubuntu. :) But my virtualenv experience is limited to typing exactly what instructions tell me to do, because, until 24 hours ago, I had _absolutely_ no idea of what it does, and now I have a vague understanding of it, which seems like an improvement. I've only ever dealt with it for CKAN.

> Did you install the package python-dev

D'oh—I had, but then created a new instance and forgot to do it again. :) That worked much better. Thank you!

There were a bunch of warnings, nothing serious looking, except for this:

```
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
```

So, for the record, this is the process that works:

```
# sudo apt-get install python-dev
# virtualenv ckan
# wget https://github.com/datacats/ckan-multisite/archive/master.zip
# unzip master.zip
# source ckan/bin/activate
# cd ckan/ckan-site-master
# pip install -r requirements.txt
```

**Comment by waldoj** [comment]
That said, I only made it another two steps. :) Then `datacats create multisite` failed on me, and asked me to post an issue:

<pre><code>
# datacats create multisite
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create multisite
It is seems to be a bug.
Please report this issue to us by creating an issue ticket at
    https://github.com/datacats/datacats/issues
so that we would be able to look into that and fix the issue.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/cli/create.py", line 61, in create_environment
    environment = Environment.new(environment_dir, '2.3', site_name, address=address, port=port)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/environment.py", line 115, in new
    name, datadir, srcdir = task.new_environment_check(path, site_name)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/task.py", line 284, in new_environment_check
    docker.require_images()
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/docker.py", line 404, in require_images
    if (not image_exists('datacats/web') or
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/docker.py", line 293, in image_exists
    return bool(_get_docker().images(name=name))
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/datacats/docker.py", line 92, in _get_docker
    api_version = version_client.version()['ApiVersion']
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/docker/client.py", line 837, in version
    return self._result(self._get(url), json=True)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
----------------------------------------
</code></pre>

**Comment by JackMc** [comment]
We usually get this issue when someone's Docker daemon hasn't been set up - have you installed docker (i.e. `wget -qO- https://get.docker.io | sh`).

**Comment by waldoj** [comment]
Yup, Docker is installed and running. Just in case, I restarted the service and tried `datacats create multisite` again—same result.

**Comment by JackMc** [comment]
Hm. I know that when I start my AWS instances I always have to have Docker running in another tmux tab - let me try and get this up and running and get to the same state on an instance as you are.

**Comment by deniszgonjanin** [comment]
@waldoj sorry, my wording there was weird. I don't think we should expect people to know virtualenv - for anybody with 20 years of unix skill, the experience of setting up multisite should be easier than this. 

I think this is very important because the people likely to use multisite will often not have much python experience, virtualenv being a very python-specific tool.

**Comment by waldoj** [comment]
Yay, I've yet again turned my ignorance into a virtue! ;)

**Comment by deniszgonjanin** [comment]
@waldoj i.e. I didn't mean to suggest you man it up and figure it out, but the exact opposite :smile:

**Comment by waldoj** [comment]
I know, I know. :)

**Comment by JackMc** [comment]
Hi there! 

We were thinking that it may be a good idea for us to just write a script that'll get you (hopefully) up and running on multisite. I'm gonna try this out and push it to the repo.

The OS I'm gonna be testing is Ubuntu 14.04, fresh VM.
- Jack

**Comment by waldoj** [comment]
:+1:

**Comment by waldoj** [comment]
I see you've done a whole mess of work on this today, including half an hour ago, so I'll stay out of it until you give me the go-ahead.

**Comment by JackMc** [comment]
So now if you have a new system, the run.sh script should detect that you don't have a virtualenv, create a virtualenv, and set up multisite/docker on your system if needed.

It'll probably work best if you just run the run.sh script on a new instance.

**Comment by JackMc** [comment]
It will do all the `apt-get install` stuffs and everything :smile:

**Comment by JackMc** [comment]
Also @waldoj make sure you read through the `ckan_multisite/config.py` file and set it up like your site before you run run.sh. :)

**Comment by waldoj** [comment]
Wow. That worked _way_ better. You simplified things enormously! I'm just at the welcome site now, and excited to poke around!
