### ISSUE TITLE
Wildcard DNS assignment?

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#22]
I just want to make sure that I understand how this works, before I set up infrastructure to test it out properly. The idea here is that I set up a wildcard DNS (e.g., `*.example.com`), and Nginx will handle requests for `newyork.example.com`, `miami.example.com`, etc. as those sites are established by CKAN Multisite?

**Comment by JackMc** [comment]
If you have a DNS server set up resolving *.example.com->127.0.0.1 and example.com->127.0.0.1, it should work. Let me know if not.

**Comment by waldoj** [comment]
:+1:

**Comment by waldoj** [comment]
I'm just getting a generic "Welcome to Nginx" page for the test CKAN instance I've established in CKAN Multisite. I pointed a domain name at the server and changed `HOSTNAME` in `ckan_multisite/config.py` to that domain. Is it possible that changing hostname after running `run.sh` for the first time doesn't change everything that needs to be changed? If need be, I can destroy this EC2 instance and start over again.

**Comment by JackMc** [comment]
That might be better, but I agree that that's not optimal.

I am planning on including a command to regenerate all nginx configuration files if you change the configuration. This shouldn't be too hard. 

I am gonna make a roadmap for MVP v2. :)

**Comment by waldoj** [comment]
So you think a reinstall will do the trick?

I'm not complaining, just looking to get it working. It's an MVP, after all. :)

**Comment by JackMc** [comment]
Yes, that might work. Alternatively, you can manually edit the configurations in `/etc/nginx/sites-available/` (they're named after the sites) and change the `server_name` directives.

**Comment by JackMc** [comment]
(Which would have the exact same impact)

**Comment by waldoj** [comment]
Oh, of course. :) Will do!

**Comment by JackMc** [comment]
Other problem may be that recently I added linking into the `/etc/nginx/sites-enabled`, so if your sites were created before then you will have to link them in yourself (also do a `git pull` to make sure you're at latest development from today):

```
ln -s /etc/nginx/sites-available/mysite /etc/nginx/sites-enabled/mysite
```

**Comment by JackMc** [comment]
If you do a pull and use `./manage.py regenerate` in the root dir of the repo, it should regenerate the configuration files.

**Comment by waldoj** [comment]
Given #24, I think we can chalk this up as resolved!
