### ISSUE TITLE
Must SECRET_KEY be in hex?

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#23]
[The value of `SECRET_KEY` in `ckan_multisite/config.py`](https://github.com/datacats/ckan-multisite/blob/4152a39d32339f13e1ee05dc6561ed3fd8b24c4b/ckan_multisite/config.py#L13) is in hex:

```
3\xfbIO\x99\xbd\x16u\xa1\x85\xad2\xf2nDm[\xc4\xad\xa1D\x97\xb4d\x93
```

This works out to:

```
3bIO   9d6u
15
d22nDm[4
d
1D  74d    3
```

Must this string be in hex, or could I replace it with anything at all? That it's hex-encoded is just confusing enough for me to think "eh, I'll just leave the default value," which of course would be a big security hole, in production.

If this is in the category of "yes, we know that this needs to be solved, but that's a fiddly detail at this point," that's A-OK by me. :) I'm mostly just curious.

**Comment by JackMc** [comment]
Anything you can! I just used this command to generate it. I can definitely make it something more obvious that it needs to be replaced:

```
tail -1 /dev/urandom
```

or something similar. Of course this can be any string but it's beneficial that it be cryptographically secure as its used to sign forms

**Comment by waldoj** [comment]
Ahhh, yes, `urandom` is, indeed, very random. :)

**Comment by waldoj** [comment]
Perhaps consider this?

`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-40}; echo;`

That'll include only A-Z, a-z, and 0-9, filtering out all of the high ASCII characters, control characters, etc., limiting it to 40 characters. Then you'll have a string that isn't quite so intimidating-looking.

**Comment by waldoj** [comment]
Perhaps the instructions could suggest that people run that to generate a new string. And, one day, the install script could do that at install time, so that the user doesn't have to do anything.

**Comment by JackMc** [comment]
:+1: That's a great idea!

**Comment by JackMc** [comment]
So with the most recent changes to the run.sh script, we automatically generate a string with this command and stick it in the configuration file (built from a template). The new configuration file is then opened in $EDITOR (or nano by default) and the docstring at the top prompts the user to fill in the configuration file:

```
python -c 'import os;os.urandom(20)' | base64
```

**PLEASE NOTE**: With these new changes, if you run run.sh again after deleting the venv it will overwrite your configuration with the one you edit together in nano, so if there's anything special in there, you can back it up with: `cp ckan_multisite/config.py ckan_multisite/config.py.bak`

**Comment by waldoj** [comment]
Nice!
