### ISSUE TITLE
Creating new site fails with DatacatsError

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#29]
Fresh install. The setup was great (really smooth). But creating a new site results in this error:

> DatacatsError: Environment data found but environment directory is missing. Try again from the new environment directory location or remove the environment data with "datacats purge"

(That's a nicely specific error message!) Seems like something's going wrong here.

**Comment by JackMc** [comment]
Huh. This shouldn't happen...

Can you try the command `cat ~/.datacats/multisite/project-dir`. This should give us a hint of where `datacats` is looking for the project directory.

**Comment by JackMc** [comment]
Also let me know if that directory exists or not.

**Comment by waldoj** [comment]
Sure, that says `/home/ubuntu/ckan-multisite/multisite`, and—as you rightly assumed—there is no directory `multisite` within `/home/ubuntu/ckan-multisite/`. (I kept the default installation name of `multisite`, in case that isn't obvious. :) There is no directory named `multisite` anywhere within `/home/ubuntu/ckan-multisite/`.

**Comment by JackMc** [comment]
Huh. This is really weird. Can you try running the following commands in the ckan-multisite directory? (This obviously isn't the right fix for the problem but might give us a hint)

```
datacats purge --delete-environment -y multisite (this may error a little bit)
datacats create multisite -in
```

**Comment by JackMc** [comment]
(If you get a command not found, you may not have activated your virtualenv. To do this run the following command in the ckan-multisite directory: `source virtualenv/bin/activate`)

**Comment by waldoj** [comment]
```
$ datacats purge --delete-environment -y multisite
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats purge --delete-environment -y multisite

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/ubuntu/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/home/ubuntu/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/cli/purge.py", line 32, in purge
    environment = Environment.load(opts['ENVIRONMENT'], opts['--site'])
  File "/home/ubuntu/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/environment.py", line 140, in load
    environment_name, data_only)
  File "/home/ubuntu/ckan-multisite/virtualenv/local/lib/python2.7/site-packages/datacats/task.py", line 140, in find_environment_dirs
    with open(datadir + '/project-dir') as pd:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/.datacats/multisite/project-dir'

----------------------------------------
```

**Comment by waldoj** [comment]
I erased and reinstalled, and I got the same error when I tried to create a new site. So I terminated the EC2 instance, started a new one, installed CKAN Multisite—and that time everything worked great.

So I'm not sure what setting was continuing to live after it should have stopped, but I'm going to close this.
