### ISSUE TITLE
multisite admin: ckan admin password setting and resetting

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#3]
Allow use of a common default admin user password for new ckan sites, and allow resetting any individual ckan site password as requested.

The multisite admin interface won't show the common default admin password or individual ckan site passwords. It will only allow resetting passwords and if set, removing the common default admin password.

The common default admin password will need to be retrievable for creating new ckan instances. Consider encrypting it with the sysadmin password so that it's not stored on-disk in plain-text.

**Comment by wardi** [comment]
@JackMc this is handled now, right? We've got the interface to set or reset admin passwords on each site

**Comment by JackMc** [comment]
Yup!
