### ISSUE TITLE
Bad gateway for all hosted sites

### ISSUE THREAD

**Issue by waldoj** [datacats/ckan-multisite#30]
Fresh EC2 server, fresh install. When I create a site, the log shows:

```
[2015-09-08 18:48:06,674: WARNING/Worker-1] Installing ckan
[2015-09-08 18:48:09,584: WARNING/Worker-1] Installing ckanext-multisitetheme
[2015-09-08 18:48:11,474: WARNING/Worker-1] Installing datapusher
[2015-09-08 18:48:13,040: WARNING/Worker-1] Installing ckan requirements
[2015-09-08 18:48:14,319: WARNING/Worker-1] Installing datapusher requirements
[2015-09-08 18:48:16,205: WARNING/Worker-1] Initializing database
[2015-09-08 18:48:25,489: WARNING/Worker-1] create done!
```

But a request for that site yields:

```
502 Bad Gateway
nginx/1.4.6 (Ubuntu)
```

The sites are listed in `/etc/nginx/sites-enabled`, but requests to their localhost port (e.g., `http://127.0.0.1:5314/`) are refused:

```
$ telnet 127.0.0.1 5314
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

Any suggestions?

**Comment by deniszgonjanin** [comment]
can you paste the output of `docker ps`?

**Comment by JackMc** [comment]
Start the site in the control panel :-)

**Comment by waldoj** [comment]
wat

I had no idea that little pencil icon was concealing start/stop functionality!

**Comment by JackMc** [comment]
Yeah... I couldn't think of a better symbol for that.

**Comment by waldoj** [comment]
(You'd think I'd have noticed the loss of that functionality. But I did not. D'oh!)

**Comment by waldoj** [comment]
> Yeah... I couldn't think of a better symbol for that.

And that's how the world got saddled with the hamburger icon. :-/

**Comment by deniszgonjanin** [comment]
We should just make that say 'Edit'. Failing that, replace it with the hamburger ;-)

**Comment by waldoj** [comment]
FWIW, I was clear that the icon meant "edit," but I assumed it would just let me edit the site's name. I don't associate "edit" with starting and stopping an instance.

**Comment by deniszgonjanin** [comment]
Yes, I agree. The main page needs some love UI-wise. Let's open an issue for UI stuff
